.................F...F.FFFF.......FFFFF....FF....F..FFFFFF.FFFFFFF.FF... [ 42%]
.....F.FF...........FFFFFF.+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Captured stderr ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[I 2025-07-07 04:32:30,265] A new study created in memory with name: no-name-96a3539c-cf0a-48b3-b7bd-575bd742547a
[W 2025-07-07 04:32:30,552] Trial 0 failed with parameters: {'n_estimators': 96, 'max_depth': 9, 'min_samples_split': 6} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:30,552] Trial 0 failed with value np.float64(nan).
[W 2025-07-07 04:32:30,988] Trial 1 failed with parameters: {'n_estimators': 187, 'max_depth': 10, 'min_samples_split': 13} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:30,988] Trial 1 failed with value np.float64(nan).
[W 2025-07-07 04:32:31,381] Trial 2 failed with parameters: {'n_estimators': 151, 'max_depth': 5, 'min_samples_split': 11} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:31,381] Trial 2 failed with value np.float64(nan).
[W 2025-07-07 04:32:31,827] Trial 3 failed with parameters: {'n_estimators': 190, 'max_depth': 11, 'min_samples_split': 15} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:31,827] Trial 3 failed with value np.float64(nan).
[W 2025-07-07 04:32:32,218] Trial 4 failed with parameters: {'n_estimators': 151, 'max_depth': 7, 'min_samples_split': 17} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:32,218] Trial 4 failed with value np.float64(nan).
[W 2025-07-07 04:32:32,525] Trial 5 failed with parameters: {'n_estimators': 95, 'max_depth': 4, 'min_samples_split': 11} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:32,525] Trial 5 failed with value np.float64(nan).
[W 2025-07-07 04:32:32,923] Trial 6 failed with parameters: {'n_estimators': 162, 'max_depth': 4, 'min_samples_split': 3} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:32,923] Trial 6 failed with value np.float64(nan).
[W 2025-07-07 04:32:33,314] Trial 7 failed with parameters: {'n_estimators': 157, 'max_depth': 4, 'min_samples_split': 16} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:33,314] Trial 7 failed with value np.float64(nan).
[W 2025-07-07 04:32:33,636] Trial 8 failed with parameters: {'n_estimators': 105, 'max_depth': 6, 'min_samples_split': 3} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:33,636] Trial 8 failed with value np.float64(nan).
[W 2025-07-07 04:32:33,950] Trial 9 failed with parameters: {'n_estimators': 117, 'max_depth': 10, 'min_samples_split': 4} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:33,950] Trial 9 failed with value np.float64(nan).
[W 2025-07-07 04:32:34,381] Trial 10 failed with parameters: {'n_estimators': 186, 'max_depth': 11, 'min_samples_split': 13} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:34,381] Trial 10 failed with value np.float64(nan).
[W 2025-07-07 04:32:34,591] Trial 11 failed with parameters: {'n_estimators': 52, 'max_depth': 8, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:34,591] Trial 11 failed with value np.float64(nan).
[W 2025-07-07 04:32:34,912] Trial 12 failed with parameters: {'n_estimators': 124, 'max_depth': 10, 'min_samples_split': 11} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:34,912] Trial 12 failed with value np.float64(nan).
[W 2025-07-07 04:32:35,232] Trial 13 failed with parameters: {'n_estimators': 116, 'max_depth': 7, 'min_samples_split': 15} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:35,232] Trial 13 failed with value np.float64(nan).
[W 2025-07-07 04:32:35,630] Trial 14 failed with parameters: {'n_estimators': 160, 'max_depth': 8, 'min_samples_split': 10} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:35,630] Trial 14 failed with value np.float64(nan).
[W 2025-07-07 04:32:36,031] Trial 15 failed with parameters: {'n_estimators': 165, 'max_depth': 13, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:36,031] Trial 15 failed with value np.float64(nan).
[W 2025-07-07 04:32:36,283] Trial 16 failed with parameters: {'n_estimators': 91, 'max_depth': 11, 'min_samples_split': 7} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:36,283] Trial 16 failed with value np.float64(nan).
[W 2025-07-07 04:32:36,698] Trial 17 failed with parameters: {'n_estimators': 178, 'max_depth': 13, 'min_samples_split': 12} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:36,698] Trial 17 failed with value np.float64(nan).
[W 2025-07-07 04:32:37,049] Trial 18 failed with parameters: {'n_estimators': 137, 'max_depth': 9, 'min_samples_split': 15} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:37,049] Trial 18 failed with value np.float64(nan).
[W 2025-07-07 04:32:37,451] Trial 19 failed with parameters: {'n_estimators': 161, 'max_depth': 7, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:37,451] Trial 19 failed with value np.float64(nan).
[W 2025-07-07 04:32:37,697] Trial 20 failed with parameters: {'n_estimators': 89, 'max_depth': 6, 'min_samples_split': 20} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:37,697] Trial 20 failed with value np.float64(nan).
[W 2025-07-07 04:32:38,095] Trial 21 failed with parameters: {'n_estimators': 170, 'max_depth': 8, 'min_samples_split': 8} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:38,095] Trial 21 failed with value np.float64(nan).
[W 2025-07-07 04:32:38,475] Trial 22 failed with parameters: {'n_estimators': 149, 'max_depth': 9, 'min_samples_split': 5} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:38,475] Trial 22 failed with value np.float64(nan).
[W 2025-07-07 04:32:38,711] Trial 23 failed with parameters: {'n_estimators': 72, 'max_depth': 10, 'min_samples_split': 19} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:38,711] Trial 23 failed with value np.float64(nan).
[W 2025-07-07 04:32:39,000] Trial 24 failed with parameters: {'n_estimators': 94, 'max_depth': 11, 'min_samples_split': 17} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:39,000] Trial 24 failed with value np.float64(nan).
[W 2025-07-07 04:32:39,307] Trial 25 failed with parameters: {'n_estimators': 101, 'max_depth': 3, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:39,308] Trial 25 failed with value np.float64(nan).
[W 2025-07-07 04:32:39,779] Trial 26 failed with parameters: {'n_estimators': 131, 'max_depth': 6, 'min_samples_split': 12} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:39,779] Trial 26 failed with value np.float64(nan).
[W 2025-07-07 04:32:40,203] Trial 27 failed with parameters: {'n_estimators': 180, 'max_depth': 10, 'min_samples_split': 7} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:40,203] Trial 27 failed with value np.float64(nan).
[W 2025-07-07 04:32:40,676] Trial 28 failed with parameters: {'n_estimators': 197, 'max_depth': 12, 'min_samples_split': 2} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:40,676] Trial 28 failed with value np.float64(nan).
[W 2025-07-07 04:32:41,012] Trial 29 failed with parameters: {'n_estimators': 127, 'max_depth': 6, 'min_samples_split': 2} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:41,012] Trial 29 failed with value np.float64(nan).
[W 2025-07-07 04:32:41,406] Trial 30 failed with parameters: {'n_estimators': 172, 'max_depth': 4, 'min_samples_split': 8} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:41,406] Trial 30 failed with value np.float64(nan).
[W 2025-07-07 04:32:41,798] Trial 31 failed with parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 15} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:41,798] Trial 31 failed with value np.float64(nan).
[W 2025-07-07 04:32:42,118] Trial 32 failed with parameters: {'n_estimators': 126, 'max_depth': 11, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:42,118] Trial 32 failed with value np.float64(nan).
[W 2025-07-07 04:32:42,497] Trial 33 failed with parameters: {'n_estimators': 141, 'max_depth': 7, 'min_samples_split': 10} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:42,497] Trial 33 failed with value np.float64(nan).
[W 2025-07-07 04:32:42,844] Trial 34 failed with parameters: {'n_estimators': 135, 'max_depth': 4, 'min_samples_split': 16} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:42,844] Trial 34 failed with value np.float64(nan).
[W 2025-07-07 04:32:43,226] Trial 35 failed with parameters: {'n_estimators': 163, 'max_depth': 10, 'min_samples_split': 10} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:43,226] Trial 35 failed with value np.float64(nan).
[W 2025-07-07 04:32:43,554] Trial 36 failed with parameters: {'n_estimators': 131, 'max_depth': 7, 'min_samples_split': 12} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:43,554] Trial 36 failed with value np.float64(nan).
[W 2025-07-07 04:32:44,148] Trial 37 failed with parameters: {'n_estimators': 197, 'max_depth': 12, 'min_samples_split': 4} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:44,148] Trial 37 failed with value np.float64(nan).
[W 2025-07-07 04:32:44,562] Trial 38 failed with parameters: {'n_estimators': 179, 'max_depth': 3, 'min_samples_split': 9} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:44,562] Trial 38 failed with value np.float64(nan).
[W 2025-07-07 04:32:44,794] Trial 39 failed with parameters: {'n_estimators': 68, 'max_depth': 10, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:44,794] Trial 39 failed with value np.float64(nan).
[W 2025-07-07 04:32:45,242] Trial 40 failed with parameters: {'n_estimators': 192, 'max_depth': 14, 'min_samples_split': 14} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:45,243] Trial 40 failed with value np.float64(nan).
[W 2025-07-07 04:32:45,477] Trial 41 failed with parameters: {'n_estimators': 82, 'max_depth': 5, 'min_samples_split': 16} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:45,477] Trial 41 failed with value np.float64(nan).
[W 2025-07-07 04:32:45,726] Trial 42 failed with parameters: {'n_estimators': 87, 'max_depth': 5, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:45,726] Trial 42 failed with value np.float64(nan).
[W 2025-07-07 04:32:46,116] Trial 43 failed with parameters: {'n_estimators': 149, 'max_depth': 15, 'min_samples_split': 7} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:46,116] Trial 43 failed with value np.float64(nan).
[W 2025-07-07 04:32:46,495] Trial 44 failed with parameters: {'n_estimators': 152, 'max_depth': 13, 'min_samples_split': 4} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:46,495] Trial 44 failed with value np.float64(nan).
[W 2025-07-07 04:32:46,733] Trial 45 failed with parameters: {'n_estimators': 74, 'max_depth': 10, 'min_samples_split': 9} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:46,733] Trial 45 failed with value np.float64(nan).
[W 2025-07-07 04:32:46,958] Trial 46 failed with parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 2} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:46,958] Trial 46 failed with value np.float64(nan).
[W 2025-07-07 04:32:47,370] Trial 47 failed with parameters: {'n_estimators': 173, 'max_depth': 6, 'min_samples_split': 6} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:47,370] Trial 47 failed with value np.float64(nan).
[W 2025-07-07 04:32:47,601] Trial 48 failed with parameters: {'n_estimators': 66, 'max_depth': 6, 'min_samples_split': 14} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:47,601] Trial 48 failed with value np.float64(nan).
[W 2025-07-07 04:32:47,840] Trial 49 failed with parameters: {'n_estimators': 74, 'max_depth': 15, 'min_samples_split': 4} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:47,840] Trial 49 failed with value np.float64(nan).
[I 2025-07-07 04:32:47,847] A new study created in memory with name: no-name-9526bbd8-3bb4-4223-ae8e-8f3e67e10203
[W 2025-07-07 04:32:48,074] Trial 0 failed with parameters: {'n_estimators': 57, 'max_depth': 5, 'min_samples_split': 5} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:48,074] Trial 0 failed with value np.float64(nan).
[W 2025-07-07 04:32:48,540] Trial 1 failed with parameters: {'n_estimators': 198, 'max_depth': 15, 'min_samples_split': 7} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:48,540] Trial 1 failed with value np.float64(nan).
[W 2025-07-07 04:32:48,843] Trial 2 failed with parameters: {'n_estimators': 111, 'max_depth': 7, 'min_samples_split': 5} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:48,843] Trial 2 failed with value np.float64(nan).
[W 2025-07-07 04:32:49,216] Trial 3 failed with parameters: {'n_estimators': 135, 'max_depth': 14, 'min_samples_split': 13} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:49,216] Trial 3 failed with value np.float64(nan).
[W 2025-07-07 04:32:49,559] Trial 4 failed with parameters: {'n_estimators': 132, 'max_depth': 3, 'min_samples_split': 3} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:49,559] Trial 4 failed with value np.float64(nan).
[W 2025-07-07 04:32:49,843] Trial 5 failed with parameters: {'n_estimators': 99, 'max_depth': 8, 'min_samples_split': 7} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:49,843] Trial 5 failed with value np.float64(nan).
[W 2025-07-07 04:32:50,242] Trial 6 failed with parameters: {'n_estimators': 165, 'max_depth': 4, 'min_samples_split': 12} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:50,242] Trial 6 failed with value np.float64(nan).
[W 2025-07-07 04:32:50,472] Trial 7 failed with parameters: {'n_estimators': 69, 'max_depth': 12, 'min_samples_split': 18} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:50,472] Trial 7 failed with value np.float64(nan).
[W 2025-07-07 04:32:50,693] Trial 8 failed with parameters: {'n_estimators': 52, 'max_depth': 9, 'min_samples_split': 20} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:50,694] Trial 8 failed with value np.float64(nan).
[W 2025-07-07 04:32:50,921] Trial 9 failed with parameters: {'n_estimators': 62, 'max_depth': 9, 'min_samples_split': 16} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:50,921] Trial 9 failed with value np.float64(nan).
[W 2025-07-07 04:32:51,148] Trial 10 failed with parameters: {'n_estimators': 59, 'max_depth': 10, 'min_samples_split': 13} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:51,148] Trial 10 failed with value np.float64(nan).
[W 2025-07-07 04:32:51,471] Trial 11 failed with parameters: {'n_estimators': 128, 'max_depth': 6, 'min_samples_split': 20} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:51,471] Trial 11 failed with value np.float64(nan).
[W 2025-07-07 04:32:51,862] Trial 12 failed with parameters: {'n_estimators': 150, 'max_depth': 9, 'min_samples_split': 3} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:51,863] Trial 12 failed with value np.float64(nan).
[W 2025-07-07 04:32:52,253] Trial 13 failed with parameters: {'n_estimators': 165, 'max_depth': 7, 'min_samples_split': 5} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:52,253] Trial 13 failed with value np.float64(nan).
[W 2025-07-07 04:32:52,650] Trial 14 failed with parameters: {'n_estimators': 149, 'max_depth': 9, 'min_samples_split': 5} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:52,651] Trial 14 failed with value np.float64(nan).
[W 2025-07-07 04:32:52,884] Trial 15 failed with parameters: {'n_estimators': 75, 'max_depth': 11, 'min_samples_split': 12} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:52,884] Trial 15 failed with value np.float64(nan).
[W 2025-07-07 04:32:53,174] Trial 16 failed with parameters: {'n_estimators': 94, 'max_depth': 7, 'min_samples_split': 8} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:53,174] Trial 16 failed with value np.float64(nan).
[W 2025-07-07 04:32:53,404] Trial 17 failed with parameters: {'n_estimators': 80, 'max_depth': 4, 'min_samples_split': 16} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:53,405] Trial 17 failed with value np.float64(nan).
[W 2025-07-07 04:32:53,723] Trial 18 failed with parameters: {'n_estimators': 106, 'max_depth': 4, 'min_samples_split': 12} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:53,723] Trial 18 failed with value np.float64(nan).
[W 2025-07-07 04:32:53,956] Trial 19 failed with parameters: {'n_estimators': 81, 'max_depth': 10, 'min_samples_split': 10} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:53,956] Trial 19 failed with value np.float64(nan).
[W 2025-07-07 04:32:54,338] Trial 20 failed with parameters: {'n_estimators': 148, 'max_depth': 14, 'min_samples_split': 3} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:54,338] Trial 20 failed with value np.float64(nan).
[W 2025-07-07 04:32:54,570] Trial 21 failed with parameters: {'n_estimators': 65, 'max_depth': 12, 'min_samples_split': 4} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:54,570] Trial 21 failed with value np.float64(nan).
[W 2025-07-07 04:32:54,875] Trial 22 failed with parameters: {'n_estimators': 95, 'max_depth': 9, 'min_samples_split': 5} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:54,875] Trial 22 failed with value np.float64(nan).
[W 2025-07-07 04:32:55,114] Trial 23 failed with parameters: {'n_estimators': 80, 'max_depth': 13, 'min_samples_split': 3} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:55,114] Trial 23 failed with value np.float64(nan).
[W 2025-07-07 04:32:55,394] Trial 24 failed with parameters: {'n_estimators': 94, 'max_depth': 10, 'min_samples_split': 8} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:55,394] Trial 24 failed with value np.float64(nan).
[W 2025-07-07 04:32:55,771] Trial 25 failed with parameters: {'n_estimators': 154, 'max_depth': 6, 'min_samples_split': 6} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:55,771] Trial 25 failed with value np.float64(nan).
[W 2025-07-07 04:32:55,995] Trial 26 failed with parameters: {'n_estimators': 54, 'max_depth': 11, 'min_samples_split': 17} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:55,995] Trial 26 failed with value np.float64(nan).
[W 2025-07-07 04:32:56,410] Trial 27 failed with parameters: {'n_estimators': 173, 'max_depth': 8, 'min_samples_split': 15} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:56,410] Trial 27 failed with value np.float64(nan).
[W 2025-07-07 04:32:56,637] Trial 28 failed with parameters: {'n_estimators': 66, 'max_depth': 10, 'min_samples_split': 19} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:56,637] Trial 28 failed with value np.float64(nan).
[W 2025-07-07 04:32:56,954] Trial 29 failed with parameters: {'n_estimators': 114, 'max_depth': 11, 'min_samples_split': 15} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:56,954] Trial 29 failed with value np.float64(nan).
[W 2025-07-07 04:32:57,367] Trial 30 failed with parameters: {'n_estimators': 179, 'max_depth': 8, 'min_samples_split': 16} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:57,367] Trial 30 failed with value np.float64(nan).
[W 2025-07-07 04:32:57,683] Trial 31 failed with parameters: {'n_estimators': 105, 'max_depth': 11, 'min_samples_split': 3} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:57,683] Trial 31 failed with value np.float64(nan).
[W 2025-07-07 04:32:57,931] Trial 32 failed with parameters: {'n_estimators': 87, 'max_depth': 5, 'min_samples_split': 4} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:57,931] Trial 32 failed with value np.float64(nan).
[W 2025-07-07 04:32:58,185] Trial 33 failed with parameters: {'n_estimators': 86, 'max_depth': 14, 'min_samples_split': 4} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:58,185] Trial 33 failed with value np.float64(nan).
[W 2025-07-07 04:32:58,649] Trial 34 failed with parameters: {'n_estimators': 192, 'max_depth': 13, 'min_samples_split': 7} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:58,649] Trial 34 failed with value np.float64(nan).
[W 2025-07-07 04:32:58,967] Trial 35 failed with parameters: {'n_estimators': 120, 'max_depth': 13, 'min_samples_split': 7} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:58,967] Trial 35 failed with value np.float64(nan).
[W 2025-07-07 04:32:59,395] Trial 36 failed with parameters: {'n_estimators': 180, 'max_depth': 7, 'min_samples_split': 9} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:59,395] Trial 36 failed with value np.float64(nan).
[W 2025-07-07 04:32:59,795] Trial 37 failed with parameters: {'n_estimators': 176, 'max_depth': 9, 'min_samples_split': 17} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:32:59,795] Trial 37 failed with value np.float64(nan).
[W 2025-07-07 04:33:00,021] Trial 38 failed with parameters: {'n_estimators': 69, 'max_depth': 11, 'min_samples_split': 14} because of the following error: The value nan is not acceptable.
[W 2025-07-07 04:33:00,021] Trial 38 failed with value np.float64(nan).
~~~~~~~~~~~~~ Stack of Thread-21133 (_handle_results) (6310834176) ~~~~~~~~~~~~~
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
~~~~~~~~~~~~~~~~~ Stack of Thread-21135 (worker) (6294007808) ~~~~~~~~~~~~~~~~~~
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1045, in _bootstrap_inner
    self._delete()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 996, in run
    del self._target, self._args, self._kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 571, in _handle_tasks
    util.debug('task handler exiting')
~~~~~~~~~~~~~~~~~ Stack of Thread-21134 (worker) (6277181440) ~~~~~~~~~~~~~~~~~~
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1045, in _bootstrap_inner
    self._delete()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 996, in run
    del self._target, self._args, self._kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 525, in _handle_workers
    util.debug('worker handler exiting')
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 503, in _wait_for_updates
    while not change_notifier.empty():
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/queues.py", line 373, in empty
    return not self._poll()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/connection.py", line 441, in _poll
    return bool(r)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/connection.py", line 1140, in wait
    with _WaitSelector() as selector:
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/selectors.py", line 409, in select
    return ready
~~~~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-2 (6142570496) ~~~~~~~~~~~~~~~~~~~~~~~~
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rich/live.py", line 29, in run
    while not self.done.wait(1 / self.refresh_per_second):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 659, in wait
    signaled = self._cond.wait(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 363, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~~~~~~~ Stack of MainThread (8322752256) ~~~~~~~~~~~~~~~~~~~~~~~
  File "/Library/Frameworks/Python.framework/Versions/3.13/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/main.py", line 336, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/main.py", line 289, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/main.py", line 343, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/main.py", line 367, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/runner.py", line 117, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/runner.py", line 136, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/runner.py", line 245, in call_and_report
    call = CallInfo.from_call(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/runner.py", line 344, in from_call
    result: TResult | None = func()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/runner.py", line 246, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/runner.py", line 178, in pytest_runtest_call
    item.runtest()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pytest_asyncio/plugin.py", line 508, in runtest
    super().runtest()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/python.py", line 1671, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/python.py", line 157, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pytest_asyncio/plugin.py", line 773, in inner
    _loop.run_until_complete(task)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 677, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/lukemckenzie/prompt-improver/tests/services/test_ml_integration.py", line 712, in test_optimization_scalability_characterization
    result = await ml_service.optimize_rules(training_data, mock_db_session)
  File "/Users/lukemckenzie/prompt-improver/src/prompt_improver/services/ml_integration.py", line 139, in optimize_rules
    study.optimize(objective, n_trials=50, timeout=300)  # 5 minute timeout
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/optuna/study/study.py", line 489, in optimize
    _optimize(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/optuna/study/_optimize.py", line 64, in _optimize
    _optimize_sequential(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/optuna/study/_optimize.py", line 161, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/Users/lukemckenzie/prompt-improver/src/prompt_improver/services/ml_integration.py", line 134, in objective
    scores = cross_val_score(model, X, y, cv=cv, scoring="roc_auc")
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 677, in cross_val_score
    cv_results = cross_validate(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 399, in cross_validate
    results = parallel(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/parallel.py", line 82, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/parallel.py", line 147, in __call__
    return self.function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 881, in _fit_and_score
    test_scores = _score(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/base.py", line 1358, in wrapper
    with config_context(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/pipeline.py", line 663, in fit
    return self
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/base.py", line 1358, in wrapper
    with config_context(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/ensemble/_forest.py", line 540, in fit
    return self
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/parallel.py", line 82, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/joblib/parallel.py", line 1743, in _get_outputs
    while len(_remaining_outputs) > 0:
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/joblib/parallel.py", line 1408, in _terminate_and_reset
    self._backend.terminate()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/joblib/_parallel_backends.py", line 328, in terminate
    self._pool = None
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 657, in terminate
    self._terminate()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/util.py", line 219, in __call__
    return res
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 726, in _terminate_pool
    if pool and hasattr(pool[0], 'terminate'):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1092, in join
    self._handle.join(timeout)
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
